// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntotzsmicitxsyqidmti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50b3R6c21pY2l0eHN5cWlkbXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODU5MzEsImV4cCI6MjA2NDI2MTkzMX0.jmC13s947O6utFzfKCwljt2j95pm1SC2xvgbh1LRVw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);